### ISSUE TITLE
ImportError: Module "dynamicforms.renderers" does not define a "TemplateHTMLRenderer" attribute/class

### ISSUE THREAD

**Issue by openHBP** [velis74/DynamicForms#251]
I've followed configuration and quick start guide with
`pip install dynamicforms`

then in settings.py

```py
INSTALLED_APPS += [
    'rest_framework',
    'corsheaders',
     'dynamicforms_legacy',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'dynamicforms.renderers.TemplateHTMLRenderer',
    )
}

DYNAMICFORMS_BASEDIR = os.path.dirname(DYNAMICFORMS_BASEDIR_FILE)

DYNAMICFORMS_TEMPLATE = 'dynamicforms/bootstrap'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(DYNAMICFORMS_BASEDIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            'libraries': {
                'dynamicforms': 'dynamicforms_legacy.templatetags.dynamicforms',
            },
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
```
But when I do ./manage.py runserver ou ./manage.py check I get the error

```sh
pat@pat-pc ~/d/p/r/backend (main)> ./manage.py check
Traceback (most recent call last):
  File "/home/pat/dev/pipenv/rumi/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/pat/dev/pipenv/rumi/.venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'dynamicforms.renderers' has no attribute 'TemplateHTMLRenderer'
```

Do I miss something?

**Comment by velis74** [comment]
Yes, you are missing an updated documentation. We have discontinued template rendering entirely and are now working only with JSON and componentdef renderers. Ultimately even componentdef will likely be transitioned to an enhanced version of OpenAPI, so that it's more standards compliant.

Sorry a result of too many years of wanting to have a bolierplate lessening tool while figuring out how best to do integration between back end and front end.

Please see how the example is configured. Documentation is very poorly maintained at this moment: we're still refactoring the code to be better reusable and more atomic.
